import {
  AngleLeftSmall,
  AngleRightSmall,
  ArrowLeftSmall,
  BellSlash,
  BasketShopping,
  CartShoppingSimple,
  Check,
  CheckCircle,
  CheckList,
  CheckListSquare,
  Crown,
  Envelope,
  EnvelopeArrowRight,
  ExclamationCircle,
  Gear,
  House,
  InfoCircle,
  LogoutBracket,
  PenLine,
  Plus,
  QuestionCircle,
  Search,
  SendAlt,
  Star,
  StarCircle,
  TagSimple,
  Trash,
  TrophySimple,
  User,
  UserCircle,
  UserMinus,
  UserPlus,
  WifiSlash,
  Xmark,
  XmarkCircle,
} from '@zappicon/react-native';
import type { ComponentType } from 'react';

const zappIconMap: Record<string, ComponentType<any>> = {
  account: User,
  'account-circle-outline': UserCircle,
  'account-plus': UserPlus,
  'account-remove-outline': UserMinus,
  'alert-circle-outline': ExclamationCircle,
  'angle-left-small': AngleLeftSmall,
  'arrow-left': ArrowLeftSmall,
  'bell-off-outline': BellSlash,
  cart: BasketShopping,
  'cart-outline': CartShoppingSimple,
  check: Check,
  'check-circle-outline': CheckCircle,
  'checkbox-marked': CheckListSquare,
  'checkbox-marked-outline': CheckList,
  'chevron-left': AngleLeftSmall,
  'chevron-right': AngleRightSmall,
  close: Xmark,
  'close-circle': XmarkCircle,
  'close-circle-outline': XmarkCircle,
  'cog-outline': Gear,
  crown: Crown,
  'delete-outline': Trash,
  'email-fast-outline': EnvelopeArrowRight,
  'email-outline': Envelope,
  'help-circle-outline': QuestionCircle,
  'home-variant': House,
  'information-outline': InfoCircle,
  'logout-variant': LogoutBracket,
  magnify: Search,
  'pencil-outline': PenLine,
  person: User,
  'person-outline': User,
  plus: Plus,
  send: SendAlt,
  'signal-off': WifiSlash,
  star: Star,
  'star-circle': StarCircle,
  'tag-outline': TagSimple,
  trophy: TrophySimple,
  'trophy-variant': TrophySimple,
  user: User,
  'user-circle': UserCircle,
  'user-minus': UserMinus,
  'user-plus': UserPlus,
  xmark: Xmark,
  'xmark-circle': XmarkCircle,
};

export default zappIconMap;
